name: Playwright C# CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Install Playwright Browsers
      run: |
        npm install -g playwright
        playwright install

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Run Playwright Tests
      run: xvfb-run --auto-servernum --server-args='-screen 0 1920x1080x24' dotnet test --no-build --configuration Release
