name: .NET Playwright CI

on: 
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 10 * * *'   # Runs daily at 3:30 PM IST

jobs:
  build-and-test:
    runs-on: [self-hosted]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Restore dependencies
      run: dotnet restore
      shell: cmd

    - name: Build project
      run: dotnet build --no-restore --configuration Release
      shell: cmd

    - name: Add .NET tools folder to PATH
      run: echo %USERPROFILE%\.dotnet\tools >> %GITHUB_PATH%
      shell: cmd

    - name: Install Playwright Browsers (automated)
      run: powershell -ExecutionPolicy Bypass -File bin\Release\net8.0\playwright.ps1 install
      shell: cmd

    - name: Run tests
      continue-on-error: true  # Allows workflow to proceed even if tests fai
      run: dotnet test --no-build --configuration Release --logger "trx"
      shell: cmd
      env: 
        HEADLESS: false

    - name: Deploy to local folder
      if: success()  # Only runs if all previous steps (except test) succeeded
      run: powershell -ExecutionPolicy Bypass -File deploy.ps1
      shell: cmd
