name: Playwright C# CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  # Change if you're using .NET 6 or 7

    - name: Restore dependencies
      run: dotnet restore

    - name: Install Playwright Browsers
      run: |
        npm install -g playwright
        playwright install

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Run Playwright Tests
      run: dotnet test --no-build --configuration Release
