name: .NET Playwright Headed CI

on: 
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: [self-hosted]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x' # Adjust based on your project

    - name: Restore dependencies
      run: dotnet restore
      shell: cmd

    - name: Build project
      run: dotnet build --configuration Release
      shell: cmd

    - name: Install Playwright Browsers
      run: pwsh bin\Debug\net8.0\playwright.ps1 install
      shell: pwsh

    - name: Run Playwright Tests (Headed)
      run: dotnet test --configuration Release
      shell: cmd
      env:
        PLAYWRIGHT_HEADLESS: false
