name: .NET Playwright CI

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build-and-test:
    runs-on: [self-hosted]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --no-restore --configuration Release

    - name: Install Playwright CLI (latest)
      run: dotnet tool install --global Microsoft.Playwright.CLI

    - name: Add .NET tools to PATH (for Playwright CLI)
      run: echo %USERPROFILE%\.dotnet\tools >> %GITHUB_PATH%

    - name: Install Playwright browsers
      run: playwright install

    - name: Run tests
      run: dotnet test --no-build --configuration Release --logger "trx"
