name: .NET Playwright CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build-and-test:
    runs-on: DESKTOP-NM837GC

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  # Use your target version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --no-restore --configuration Release

    - name: Install Playwright browsers
      run: pwsh ./bin/Release/net8.0/playwright.ps1 install

    - name: Run tests with xvfb (headed mode)
      run: xvfb-run dotnet test --no-build --configuration Release --logger "trx"

    # - name: Run tests in headless mode (recommended)
    #   run: dotnet test --no-build --configuration Release --logger "trx"

      
