name: .NET Playwright CI

on: 
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: [self-hosted]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set safe Git directory (for self-hosted runners)
      run: git config --global --add safe.directory "${{ github.workspace }}"

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --no-restore --configuration Release

    - name: Install Playwright Browsers
      run: |
        dotnet tool restore
        dotnet playwright install

    - name: Run tests (capture failure but continue)
      run: |
        dotnet test --no-build --configuration Release --logger "trx;LogFileName=test-results.trx" || echo "Test failures occurred."
      
    - name: Deploy or Copy Report to Folder (always runs)
      if: always()
      run: powershell -ExecutionPolicy Bypass -File deploy.ps1
