name: .NET Playwright CI

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build-and-test:
    runs-on: [self-hosted]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Manually install .NET SDK to custom directory
      run: |
        $dotnetRoot = "C:\actions-runner\dotnet"
        $env:DOTNET_INSTALL_DIR = $dotnetRoot
        Invoke-WebRequest -Uri https://dot.net/v1/dotnet-install.ps1 -OutFile dotnet-install.ps1
        pwsh ./dotnet-install.ps1 -Channel 8.0 -InstallDir $dotnetRoot
      shell: pwsh

    - name: Add custom .NET SDK to PATH
      run: echo "C:\actions-runner\dotnet" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --no-restore --configuration Release

    - name: Add .dotnet tools to PATH
      run: echo "$env:USERPROFILE\.dotnet\tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8

    - name: Install Playwright CLI (global tool)
      run: dotnet tool install --global Microsoft.Playwright.CLI --version 1.37.0

    - name: Install Playwright browsers
      run: playwright install

    - name: Run tests
      run: dotnet test --no-build --configuration Release --logger "trx"
