name: .NET Playwright CI

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

    
jobs:
  run-on-selfhost:
    name: Run on Self-Hosted Runner
    runs-on: [self-hosted]
    continue-on-error: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore dependencies
        run: dotnet restore
        shell: cmd

      - name: Build project
        run: dotnet build --no-restore --configuration Release
        shell: cmd

      - name: Add .NET tools folder to PATH
        run: echo %USERPROFILE%\.dotnet\tools >> %GITHUB_PATH%
        shell: cmd

      - name: Install Playwright Browsers
        run: powershell -ExecutionPolicy Bypass -File bin\Release\net8.0\playwright.ps1 install
        shell: cmd

      - name: Run tests
        run: dotnet test --no-build --configuration Release --logger "trx"
        shell: cmd
        env:
          HEADLESS: false

      - name: Deploy to local folder
        if: success()
        run: powershell -ExecutionPolicy Bypass -File deploy.ps1
        shell: cmd

  run-on-ubuntu:
    name: Run on Ubuntu VM
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --no-restore --configuration Release

      - name: Install Playwright Browsers
        run: pwsh bin/Release/net8.0/playwright.ps1 install

      - name: Run tests with xvfb
        run: xvfb-run --auto-servernum dotnet test --no-build --configuration Release --logger "trx"
        env:
          HEADLESS: true

      - name: Zip test output
        run: zip -r test_output.zip .

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-test-output
          path: test_output.zip
