name: .NET Playwright CI

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build-and-test:
    runs-on: [self-hosted]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # - name: Add .NET tools to PATH
    #   shell: powershell
    #   run: echo "$env:USERPROFILE\.dotnet\tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8

    - name: Restore dependencies
      shell: powershell
      run: dotnet restore

    - name: Build project
      shell: powershell
      run: dotnet build --no-restore --configuration Release

    - name: Install Playwright CLI (latest)
      shell: powershell
      run: dotnet tool install --global Microsoft.Playwright.CLI

    - name: Install Playwright browsers
      shell: powershell
      run: playwright install

    - name: Run tests
      shell: powershell
      run: dotnet test --no-build --configuration Release --logger "trx"
