name: .NET Playwright CI

on: 
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: [self-hosted]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set environment variables
      shell: powershell
      run: |
        Add-Content -Path $env:GITHUB_ENV -Value "HEADLESS=false"
        Add-Content -Path $env:GITHUB_ENV -Value "PLAYWRIGHT_BROWSERS_PATH=0"
        Add-Content -Path $env:GITHUB_ENV -Value "DOTNET_ROOT=$env:USERPROFILE\.dotnet"

    - name: Restore dependencies
      run: dotnet restore
      shell: cmd

    - name: Build project
      run: dotnet build --no-restore --configuration Release
      shell: cmd

    - name: Install Playwright CLI (latest)
      run: dotnet tool install --global Microsoft.Playwright.CLI
      shell: cmd

    - name: Add .NET tools folder to PATH
      run: echo %USERPROFILE%\.dotnet\tools >> %GITHUB_PATH%
      shell: cmd

    - name: Install Playwright Browsers (automated)
      run: powershell -ExecutionPolicy Bypass -File bin\Release\net8.0\playwright.ps1 install
      shell: cmd

    - name: Run tests
      run: dotnet test --no-build --configuration Release --logger "trx"
      shell: cmd

    - name: Deploy to local folder
      if: success()
      run: powershell -ExecutionPolicy Bypass -File deploy.ps1
      shell: cmd
