name: .NET Playwright CI

on: 
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: [self-hosted]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set environment variables for headed mode
      run: |
        echo "HEADLESS=false" >> $env:GITHUB_ENV
        echo "PLAYWRIGHT_BROWSERS_PATH=0" >> $env:GITHUB_ENV
        echo "DOTNET_ROOT=$env:USERPROFILE\.dotnet" >> $env:GITHUB_ENV
      shell: pwsh

    - name: Restore dependencies
      run: dotnet restore
      shell: pwsh

    - name: Build project
      run: dotnet build --no-restore --configuration Release
      shell: pwsh

    - name: Install Playwright CLI (latest)
      run: dotnet tool install --global Microsoft.Playwright.CLI
      shell: pwsh

    - name: Add .NET tools folder to PATH
      run: echo "$env:USERPROFILE\.dotnet\tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      shell: pwsh

    - name: Install Playwright Browsers
      run: |
        pwsh -ExecutionPolicy Bypass -Command "bin\Release\net8.0\playwright.ps1 install"
      shell: pwsh

    - name: Run tests (headed mode)
      run: dotnet test --no-build --configuration Release --logger "trx"
      shell: pwsh

    - name: Deploy to local folder
      if: success()
      run: |
        pwsh -ExecutionPolicy Bypass -File deploy.ps1
      shell: pwsh
